routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CRUDController;
use App\Http\Controllers\Auth\AuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [AuthController::class, 'dashboard']); 


Route::resource('my-crud', CRUDController::class);

Route::get('login', [AuthController::class, 'index'])->name('login');
Route::post('post-login', [AuthController::class, 'postLogin'])->name('login.post'); 
Route::get('registration', [AuthController::class, 'registration'])->name('register');
Route::post('post-registration', [AuthController::class, 'postRegistration'])->name('register.post'); 
Route::get('dashboard', [AuthController::class, 'dashboard']); 
Route::get('logout', [AuthController::class, 'logout'])->name('logout');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CRUDController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use Illuminate\Http\Request;

class CRUDController extends Controller
{
    
    public function index()
    {
        $students = Student::paginate(10);
        return view('crud.index',compact('students'));
    }

    
    public function create()
    {
        return view('crud.create');
    }

    
    public function store(Request $request)
    {
        // Validate the Field
        $this->validate($request,
            [
                'name'=>'required',
                'roll'=>'required',
                'email'=>'required|email|unique:students,email',
                'phone'=>'required|regex:/^([0-9\s\-\+\(\)]*)$/|min:10',
                'address'=>'required',
                'image' => 'required|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ],

            [
                'image.mimes' => 'File Type Error : Image must be of type jpg, jpeg, png',
                // 'email.unique' => 'Email ID already exists...'
            ],

            [
                'name' => 'First Name',
                'roll' => 'Roll No',
                'email' => 'Email Address',
                'phone' => 'Contact Number',
                'address' => 'Address',
                'image' => 'Photo'
            ]
        );

        $student = new Student();
        $student->roll=$request->roll;
        $student->name=$request->name;
        $student->email=$request->email;
        $student->phone=$request->phone;
        $student->address=$request->address;
        $student->image=$request->file('image')->store('/');
        $student->save();
        return redirect()->route('my-crud.index')->with('message','New Student Created Successfull !');

    }

    
    public function show($id)
    {
        $student = Student::find($id);
        return view('crud.read',compact('student'));
    }


    
    public function edit($id)
    {
        $student = Student::find($id);
        return view('crud.edit',compact('student'));
    }

    
    public function update(Request $request, $id)
    {
        // Validate the Field
        $this->validate($request,
            [
                'name'=>'required',
                'roll'=>'required',
                'email'=>'required|email|unique:students,email,{$this->student->id}',
                'phone'=>'required|regex:/^([0-9\s\-\+\(\)]*)$/|min:10',
                'address'=>'required',
                'image' => 'required|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ],

            [
                'image.mimes' => 'File Type Error : Image must be of type jpg, jpeg, png'
            ],
            
            [
                'name' => 'First Name',
                'roll' => 'Roll No',
                'email' => 'Email Address',
                'phone' => 'Contact Number',
                'address' => 'Address',
                'image' => 'Photo'
            ]
        );


        $student = Student::find($id);
        $student->roll=$request->roll;
        $student->name=$request->name;
        $student->email=$request->email;
        $student->phone=$request->phone;
        $student->address=$request->address;
        $student->image=$request->file('image')->store('/');
        $student->save();
        return redirect()->route('my-crud.index')->with('message','Student Updated Successfull !');
    }

    
    public function destroy($id)
    {
        $student = Student::find($id)->delete();
        return back()->with('message','Student Deleted Successfull !');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/crud/create.blade.php
@extends('crud.main')
   
@section('main-content')
   
<div class="container">
	<div>
  		<br><br>
  	</div>
	<div class="row justify-content-center">
    	<div class="col-md-8">
        	<div class="card">
				<div class="card-header">
      				<center><h3>Create New Student</center></h3>
				</div>

      			<div class="card-body">
      			@if ($errors->any())
					<div class="alert alert-danger">
					    <ul>
					        @foreach ($errors->all() as $error)
					            <li>{{ $error }}</li>
					        @endforeach
					    </ul>
					</div>
				@endif
	 	 		<form action="{{ route('my-crud.store') }}" method="post" enctype="multipart/form-data">
	 	 		{{ csrf_field() }}
			  	<div class="row">
			  		<div class="col-md-4">
			  			<div class="form-group">
				    		<label for="roll">Roll Number</label>
				    		<input type="text" class="form-control" placeholder="Roll Number" name="roll" id="email" value="{{ old('roll') }}">
				 		</div>
			  		</div>
			  		<div class="col-md-8">
			  			<div class="form-group">
				    		<label for="roll">Student Name<span class="required">*</span></label>
				    		<input type="text" class="form-control" placeholder="Student Name" name="name" id="name" value="{{ old('name') }}">
				 		</div>
			  		</div>
			  		<div class="col-md-6">
			  			<div class="form-group">
							<label for="email">Email</label>
						    <input type="email" class="form-control" placeholder="Email" name="email" id="email" value="{{ old('email') }}">
						</div>
			  		</div>
			  		<div class="col-md-6">
			  			<div class="form-group">
						    <label for="phone">Phone</label>
						    <input type="text" class="form-control" placeholder="Phone" name="phone" id="phone" value="{{ old('phone') }}">
						</div>
			  		</div>
			    	<div class="col-md-12">
			  			<div class="form-group">
					    	<label for="address">Address</label>
					    	<input type="text" class="form-control" placeholder="Address" name="address" id="address" value="{{ old('address') }}">
					 	</div>
			  		</div>
					<div class="col-md-12">
            			<div class="form-group">
							<label for="image">Image</label>
                			<input type="file" name="image" class="form-control" placeholder="image" value="{{ old('image') }}">
            			</div>
        			</div>
			  	</div>
			  	<button type="submit" class="btn btn-primary">Add</button>
			  	<a href="{{ route('my-crud.index') }}" class="btn btn-danger">Back</a>
				</form> 
			</div>

   	  	</div>
	  
    </div>
	
</div>
    
@endsection

resources/views/crud/edit.blade.php
@extends('crud.main')
   
@section('main-content')
   
<div class="container">
	<div>
  		<br><br>
  	</div>
	<div class="row justify-content-center">
    	<div class="col-md-8">
        	<div class="card">
				<div class="card-header">
      				<center><h3>Edit Student</center></h3>
				</div>
				<div class="card-body">
      				@if ($errors->any())
					    <div class="alert alert-danger">
					        <ul>
					            @foreach ($errors->all() as $error)
					                <li>{{ $error }}</li>
					            @endforeach
					        </ul>
					    </div>
					@endif
	 	 			<form action="{{ route('my-crud.update',$student->id) }}" method="post"  enctype="multipart/form-data">
	 	 				{{ csrf_field() }}
	 	 				{{ method_field('PATCH') }}
					  <div class="row">
					  	<div class="col-md-4">
					  	<div class="form-group">
						    <label for="roll">Roll Number</label>
						    <input type="text" value="{{ $student->roll }}" class="form-control" placeholder="Roll Number" name="roll" id="email">
						 </div>
					  	</div>
					  	<div class="col-md-8">
					  	<div class="form-group">
						    <label for="roll">Student Name</label>
						    <input type="text" value="{{ $student->name }}" class="form-control" placeholder="Student Name" name="name" id="name">
						 </div>
					  	</div>
					  	<div class="col-md-6">
					  	<div class="form-group">
						    <label for="email">Email</label>
						    <input type="email" value="{{ $student->email }}" class="form-control" placeholder="Email" name="email" id="email">
						 </div>
					  	</div>
					  	<div class="col-md-6">
					  	<div class="form-group">
						    <label for="phone">Phone</label>
						    <input type="text" value="{{ $student->phone }}" class="form-control" placeholder="Phone" name="phone" id="phone">
						 </div>
					  	</div>
					        <div class="col-md-12">
					  	<div class="form-group">
						    <label for="address">Address</label>
						    <input type="text" value="{{ $student->address }}" class="form-control" placeholder="Address" name="address" id="address">
						 </div>
					  	</div>
					        <div class="col-md-12">
					  	<div class="form-group">
						    <label for="image">Image</label>
						    <input type="file" value="{{ $student->image }}" class="form-control" placeholder="image" name="image" id="image">
						 </div>
					  	</div>
					  </div>
					  <button type="submit" class="btn btn-success">Update</button>
					  <a href="{{ route('my-crud.index') }}" class="btn btn-danger">Back</a>
					</form>
				</div>

   	  		</div>
	  
    	</div>
	
	</div>
	
</div>
   	  
@endsection

resources/views/crud/index.blade.php
 
@extends('crud.main')
   
@section('main-content')
   
<div class="container">
	<div>
  		<br><br>
  	</div>
     @if(Session::has('message'))
     	<p class="alert alert-success">{{ Session::get('message') }}</p>
     @endif
 	<div class="panel panel-primary">
      <div class="panel-heading">
		<a href="{{ route('my-crud.create') }}" data-toggle="modal" data-target="#addModal" class="btn btn-sm btn-success"><i class="fa fa-plus-circle"></i> Add New</a>
      </div>
      <div class="panel-body">
	 	<table class="table table-hover table-bordered table-stripped">
	 		<thead>
	 			<tr>
	 			<th>S.N</th>
	 			<th>Name</th>
	 			<th>Roll No.</th>
	 			<th>Phone</th>
	 			<th>Email</th>
	 			<th>Address</th>
	 			<th>Image</th>
	 			<th style="width:200px;">Action</th>
	 			</tr>
	 		</thead>
	 		<tbody>
	 		    @foreach ($students as $student)
	 			<tr>
	 			<td>{{ $loop->index+1 }}</td>
	 			<td>{{ $student->name }}</td>
	 			<td>{{ $student->roll }}</td>
	 			<td>{{ $student->phone }}</td>
	 			<td>{{ $student->email }}</td>
	 			<td>{{ $student->address }}</td>
				<td><img src="http://localhost/multigraphics/storage/app/{{ $student->image }}" width="100px"></td>
	 			<td>
	 		<form  method="post" action="{{ route('my-crud.destroy',$student->id) }}" class="delete_form">
                	        {{ csrf_field() }}
                		{{ method_field('DELETE') }}
                		<a href="{{ route('my-crud.edit',$student->id) }}" class="btn btn-xs btn-primary"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                		
						<a href="{{ route('my-crud.show',$student->id) }}" class="btn btn-xs btn-success"><i class="fa fa-eye" aria-hidden="true"></i></a>


                        <button class="btn btn-xs btn-danger" type="submit" onclick="return confirm('Are You Sure? Want to Delete It.');"><i class="fa fa-trash" aria-hidden="true"></i></button>
                	</form>
	 		</td>
	 		</tr>
	 		@endforeach
	 		</tbody>
	 	</table>
	 	
   	  </div>
    </div>
</div>
    
@endsection

resources/views/crud/main.blade.php
<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <title>Yadavendra - MY CRUD</title>
  </head>
  <body>
    
   
    @section('main-content')

    

    @show

    
    <script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>

resources/views/crud/read.blade.php
@extends('crud.main')
   
@section('main-content')
   
<div class="container">
  	<div>
  		<br><br>
  	</div>
	<div class="row justify-content-center">
    	<div class="col-md-8">
        	<div class="card">
				<div class="card-header">
      				<center><h3>View Student Details</center></h3>
				</div>
      			<div class="col-md-12">
					<div class="form-group">
        		    	<center><label for="image">Image</label><br>
        		    	<img disabled src="http://localhost/multigraphics/storage/app/{{ $student->image }}" width="100px"></center>
					</div>
				</div>
      			<div class="card-body">
					<div class="row">
					  	<div class="col-md-4">
					  		<div class="form-group">
						    	<label for="roll">Roll Number</label>
						    	<input type="text" disabled value="{{ $student->roll }}" class="form-control" placeholder="Roll Number" name="roll" id="email">
						 	</div>
					  	</div>
					  	<div class="col-md-8">
					  		<div class="form-group">
						    	<label for="roll">Student Name</label>
						    	<input type="text" disabled value="{{ $student->name }}" class="form-control" placeholder="Student Name" name="name" id="name">
						 	</div>
					  	</div>
					  	<div class="col-md-6">
					  		<div class="form-group">
						    	<label for="email">Email</label>
						    	<input type="email" disabled value="{{ $student->email }}" class="form-control" placeholder="Email" name="email" id="email">
						 	</div>
					  	</div>
					  	<div class="col-md-6">
					  		<div class="form-group">
						    	<label for="phone">Phone</label>
						    	<input type="text" disabled value="{{ $student->phone }}" class="form-control" placeholder="Phone" name="phone" id="phone">
						 	</div>
					  	</div>
					    <div class="col-md-12">
					  		<div class="form-group">
						    	<label for="address">Address</label>
						    	<input type="text" disabled value="{{ $student->address }}" class="form-control" placeholder="Address" name="address" id="address">
						 	</div>
					  	</div>
					</div>
					<a href="{{ route('my-crud.index') }}" class="btn btn-danger">Back</a>
   	  			</div>
			</div>
		</div>
    </div>
</div>
    
@endsection

resources/views/dashboard.blade.php
@extends('layout')
  
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>
  
                <div class="card-body">
                    @if (session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                    @endif
  
                    <div class="panel-heading">
                        <h6>Students Record: <br><br>
		                <a href="{{ route('my-crud.index') }}" class="btn btn-sm btn-success">All Students</a>
		                <a href="{{ route('my-crud.create') }}" class="btn btn-sm btn-primary">Add New Students</a>
                        </h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Yadavendra Yadav - My AUTH Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <style type="text/css">
        @import url(https://fonts.googleapis.com/css?family=Raleway:300,400,600);
  
        body{
            margin: 0;
            font-size: .9rem;
            font-weight: 400;
            line-height: 1.6;
            color: #212529;
            text-align: left;
            background-color: #f5f8fa;
        }
        .navbar-laravel
        {
            box-shadow: 0 2px 4px rgba(0,0,0,.04);
        }
        .navbar-brand , .nav-link, .my-form, .login-form
        {
            font-family: Raleway, sans-serif;
        }
        .my-form
        {
            padding-top: 1.5rem;
            padding-bottom: 1.5rem;
        }
        .my-form .row
        {
            margin-left: 0;
            margin-right: 0;
        }
        .login-form
        {
            padding-top: 1.5rem;
            padding-bottom: 1.5rem;
        }
        .login-form .row
        {
            margin-left: 0;
            margin-right: 0;
        }
    </style>
</head>
<body>
    
<nav class="navbar navbar-expand-lg navbar-light navbar-laravel">
    <div class="container">
        <a class="navbar-brand">Hello {{ isset(Auth::user()->name) ? Auth::user()->name : "Visitor" }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
   
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">Register</a>
                    </li>
                @else
                    <li class="nav-item">
                    <a class="nav-link" href="{{ route('logout') }}">Logout</a>
                    </li>
                @endguest
            </ul>
  
        </div>
    </div>
</nav>
  
@yield('content')
     
</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</html>